In [3]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [4]:
cred = pd.read_csv('german_credit.csv')
cred.head()

default account_check_status  duration_in_month  \
0        0               < 0 DM                  6   
1        1    0 <= ... < 200 DM                 48   
2        0  no checking account                 12   
3        0               < 0 DM                 42   
4        1               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex  ... present_res_since  \
0                        male : single  ...                 4   
1  female : divorced/separated/married  ...                 2   
2                        male : single  ...                 3   
3                        male : single  ...                 4   
4                        male : single  ...                 4   

                                            property age  \
0                                        real estate  67   
1                                        real estate  22   
2                                        real estate  49   
3  if not A121 : building society savings agreeme...  45   
4                              unknown / no property  53   

   other_installment_plans   housing credits_this_bank  \
0                     none       own                 2   
1                     none       own                 1   
2                     none       own                 1   
3                     none  for free                 1   
4                     none  for free                 2   

                           job people_under_maintenance  \
0  skilled employee / official                        1   
1  skilled employee / official                        1   
2         unskilled - resident                        2   
3  skilled employee / official                        2   
4  skilled employee / official                        2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes  

[5 rows x 21 columns]

In [5]:
cred.shape

(1000, 21)

In [6]:
cred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000

In [0]:
# You can access from https://www.kaggle.com/uciml/german-credit
#Read input file and understand the data
# "default" is my dependent variable

(1000, 21)
Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')


default account_check_status  duration_in_month  \
0        0               < 0 DM                  6   
1        1    0 <= ... < 200 DM                 48   
2        0  no checking account                 12   
3        0               < 0 DM                 42   
4        1               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex      ...       present_res_since  \
0                        male : single      ...                       4   
1  female : divorced/separated/married      ...                       2   
2                        male : single      ...                       3   
3                        male : single      ...                       4   
4                        male : single      ...                       4   

                                            property age  \
0                                        real estate  67   
1                                        real estate  22   
2                                        real estate  49   
3  if not A121 : building society savings agreeme...  45   
4                              unknown / no property  53   

   other_installment_plans   housing credits_this_bank  \
0                     none       own                 2   
1                     none       own                 1   
2                     none       own                 1   
3                     none  for free                 1   
4                     none  for free                 2   

                           job people_under_maintenance  \
0  skilled employee / official                        1   
1  skilled employee / official                        1   
2         unskilled - resident                        2   
3  skilled employee / official                        2   
4  skilled employee / official                        2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes  

[5 rows x 21 columns]

### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
# Copy all the independent/predictor variables into X dataframe. Since 'default' is dependent variable drop it
X = cred.drop('default', axis=1)

# Copy the 'default' column alone into the y dataframe. This is the dependent variable
y = cred[['default']]

In [10]:
X.head()

account_check_status  duration_in_month  \
0               < 0 DM                  6   
1    0 <= ... < 200 DM                 48   
2  no checking account                 12   
3               < 0 DM                 42   
4               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex other_debtors  present_res_since  \
0                        male : single          none                  4   
1  female : divorced/separated/married          none                  2   
2                        male : single          none                  3   
3                        male : single     guarantor                  4   
4                        male : single          none                  4   

                                            property  age  \
0                                        real estate   67   
1                                        real estate   22   
2                                        real estate   49   
3  if not A121 : building society savings agreeme...   45   
4                              unknown / no property   53   

  other_installment_plans   housing  credits_this_bank  \
0                    none       own                  2   
1                    none       own                  1   
2                    none       own                  1   
3                    none  for free                  1   
4                    none  for free                  2   

                           job  people_under_maintenance  \
0  skilled employee / official                         1   
1  skilled employee / official                         1   
2         unskilled - resident                         2   
3  skilled employee / official                         2   
4  skilled employee / official                         2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes

In [11]:
y.head()

default
0        0
1        1
2        0
3        0
4        1

In [12]:
# Split X and y into training and test set in 50:50 ratio

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=1)

In [14]:
from sklearn.model_selection import train_test_split
train_data,test_data = train_test_split(cred,test_size=0.5,shuffle=True,stratify=cred['default'])
print(train_data.shape,test_data.shape)
y_train = train_data['default']
x_train = train_data.drop('default',inplace=False,axis=1)

(500, 21) (500, 21)


In [0]:
# Lets build a Ensemble model but need to modify the dataset first


### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [65]:
cred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000

In [66]:
cred.columns

Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')

In [16]:

# Print Shape of model data
x_train_data_tf=pd.get_dummies(x_train)
x_train_data_tf.shape

(500, 61)

In [0]:
# Print Shape of model data

(500, 61)

### Check for highly correlated variables but don't required any treatment for this use case

In [17]:
x_train_data_tf.corr()

duration_in_month  \
duration_in_month                                            1.000000   
credit_amount                                                0.549852   
installment_as_income_perc                                   0.143568   
present_res_since                                            0.014543   
age                                                          0.000521   
credits_this_bank                                            0.036925   
people_under_maintenance                                    -0.035242   
account_check_status_0 <= ... < 200 DM                      -0.002886   
account_check_status_< 0 DM                                  0.013142   
account_check_status_>= 200 DM / salary assignm...          -0.039220   
account_check_status_no checking account                     0.010236   
credit_history_all credits at this bank paid ba...           0.038278   
credit_history_critical account/ other credits ...          -0.001958   
credit_history_delay in paying off in the past               0.159404   
credit_history_existing credits paid back duly ...          -0.152693   
credit_history_no credits taken/ all credits pa...           0.120550   
purpose_(vacation - does not exist?)                        -0.040133   
purpose_business                                             0.224266   
purpose_car (new)                                           -0.122759   
purpose_car (used)                                           0.221385   
purpose_domestic appliances                                 -0.109482   
purpose_education                                            0.011791   
purpose_furniture/equipment                                  0.036287   
purpose_radio/television                                    -0.032156   
purpose_repairs                                             -0.064825   
purpose_retraining                                          -0.071555   
savings_.. >= 1000 DM                                       -0.036693   
savings_... < 100 DM                                        -0.025565   
savings_100 <= ... < 500 DM                                  0.019374   
savings_500 <= ... < 1000 DM                                 0.009149   
...                                                               ...   
present_emp_since_.. >= 7 years                              0.063239   
present_emp_since_... < 1 year                              -0.087691   
present_emp_since_1 <= ... < 4 years                        -0.007990   
present_emp_since_4 <= ... < 7 years                         0.050907   
present_emp_since_unemployed                                -0.046660   
personal_status_sex_female : divorced/separated...          -0.144888   
personal_status_sex_male : divorced/separated                0.003460   
personal_status_sex_male : married/widowed                  -0.116738   
personal_status_sex_male : single                            0.196513   
other_debtors_co-applicant                                   0.035946   
other_debtors_guarantor                                     -0.070004   
other_debtors_none                                           0.029545   
property_if not A121 : building society savings...          -0.067497   
property_if not A121/A122 : car or other, not i...           0.124278   
property_real estate                                        -0.250267   
property_unknown / no property                               0.220902   
other_installment_plans_bank                                 0.024845   
other_installment_plans_none                                -0.063530   
other_installment_plans_stores                               0.079226   
housing_for free                                             0.167997   
housing_own                                                 -0.101911   
housing_rent                                                -0.015059   
job_management/ self-employed/ highly qualified...           0.129728   
job_skilled employee / official      

### Drop the original variables which are converted to dummy

In [ ]:
#Once converted to dummies original variable gets removed.

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [20]:

x_train,x_test,y_train,y_test = train_test_split(x_train_data_tf,y_train,test_size=0.3)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(350, 61) (150, 61) (350,) (150,)


### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [21]:

from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)
random_forest_model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
            oob_score=False, random_state=9999, verbose=0,
            warm_start=False)

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_predicted = random_forest_model.predict(x_test)
print("confusion matrix")
print(confusion_matrix(y_test,y_predicted))
print('')
print("accuracy score")
print(accuracy_score(y_test,y_predicted))

confusion matrix
[[100   3]
 [ 34  13]]

accuracy score
0.7533333333333333


### Q6 Show the list of the features importance( 1 Marks)

In [23]:
feature_importance=random_forest_model.feature_importances_
feature_importance

array([0.07658557, 0.10956291, 0.03426222, 0.0312496 , 0.08690734,
       0.01907397, 0.00965664, 0.0156525 , 0.03491385, 0.00989953,
       0.03831518, 0.00999537, 0.0280835 , 0.00983266, 0.01524257,
       0.00759508, 0.00801304, 0.00942787, 0.02247423, 0.00806986,
       0.01518722, 0.00301975, 0.00170885, 0.01217909, 0.00147288,
       0.00032647, 0.00476557, 0.01819868, 0.00791519, 0.00628572,
       0.00982007, 0.01221045, 0.01966796, 0.01378556, 0.01371455,
       0.00582182, 0.01521195, 0.00617329, 0.01116857, 0.01563256,
       0.00630911, 0.00615223, 0.00802508, 0.01205184, 0.01537479,
       0.0226591 , 0.01141562, 0.0112857 , 0.01517964, 0.00621267,
       0.00660627, 0.01546586, 0.01288217, 0.01099845, 0.01440879,
       0.00246541, 0.0141284 , 0.0117141 , 0.01391231, 0.00177501,
       0.00189777])

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [24]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [25]:
# Use below values
num_folds = 10
seed = 77

In [0]:
#Validate the Random Forest model build above using k fold

In [30]:
k_fold=KFold(n_splits=num_folds,random_state=seed)
scores=cross_val_score(random_forest_model,x_train,y_train,cv=k_fold)
scores

array([0.8       , 0.71428571, 0.71428571, 0.8       , 0.62857143,
       0.8       , 0.85714286, 0.74285714, 0.71428571, 0.85714286])

In [0]:
#Calculate Mean score

In [31]:

scores.mean()

0.7628571428571428

In [0]:
# Calculate score standard deviation using std()

In [32]:

scores.std()

0.06886840453253686

# Q8 Print the confusion matrix( 1 Marks)

In [33]:

confusion_matrix(y_test,y_predicted)

array([[100,   3],
       [ 34,  13]], dtype=int64)

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [34]:

from sklearn.metrics import recall_score,precision_score

In [35]:

print('recall {}'.format(recall_score(y_test,y_predicted)))
print('precision {}'.format(precision_score(y_test,y_predicted)))

recall 0.2765957446808511
precision 0.8125


# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [0]:
#Hint: Use roc_curve

In [36]:

from sklearn.metrics import roc_curve
roc_curve(y_test,y_predicted)

(array([0.        , 0.02912621, 1.        ]),
 array([0.        , 0.27659574, 1.        ]),
 array([2, 1, 0], dtype=int64))

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

In [37]:
from sklearn.metrics import roc_auc_score

In [38]:

roc_auc_score(y_test,y_predicted)

0.6237347655443091

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [39]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [46]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(x_train, y_train)
    random_forest_model.fit(X_, y_)
    y_pred = random_forest_model.predict(x_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [47]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  nan
Standard deviation:  nan
